Resources:

  # A custom API Gateway account to allow us to enable request logging.
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt: [ RoleAPIGatewayCloudWatch, Arn ]

  # A custom API Gateway stage (usually handled automatically by the Serverless
  # framework) so that we can turn on CloudWatch request logging. The
  # "MethodSettings" of a stage apply to all methods (effectively all endpoints)
  # within that stage. The ApiGatewayRestApi resource is generated automatically
  # by the Serverless framework.
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: ApiGatewayRestApi
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: /*
          MetricsEnabled: true
